### ISSUE TITLE
Bug:  stats generator is not tolerating various edge cases 

### ISSUE THREAD

**Issue by eladyaniv01** [aiarena/aiarena-web#205]
this is the suspected  chunk of the log taken from production 
```js
  File "/home/aiarena/ai-arena/aiarena/frontend/views.py", line 340, in get_context_data
    context['updated'] = context['competition_bot_matchups'][0].updated
  File "/home/aiarena/ai-arena/venv/lib/python3.7/site-packages/django/db/models/query.py", line 314, in __getitem__
    return qs._result_cache[0]
```

Here is the entire log regarding that request 
```
ERROR 2021-02-02 12:34:30,783 log 17158 140600417363712 Internal Server Error: /competitions/stats/206/jensiiibot-sc2-ai-arena-pre-season
Traceback (most recent call last):
  File "/home/aiarena/ai-arena/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/aiarena/ai-arena/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/aiarena/ai-arena/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aiarena/ai-arena/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/aiarena/ai-arena/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/aiarena/ai-arena/venv/lib/python3.7/site-packages/django/views/generic/detail.py", line 107, in get
    context = self.get_context_data(object=self.object)
  File "/home/aiarena/ai-arena/aiarena/frontend/views.py", line 340, in get_context_data
    context['updated'] = context['competition_bot_matchups'][0].updated
  File "/home/aiarena/ai-arena/venv/lib/python3.7/site-packages/django/db/models/query.py", line 314, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
```

**Comment by Immodal** [comment]
Am I right in assuming `CompetitionBotMatchupStats` is created periodically, so until the creation job is run none would exist which would cause this error to occur?

If so, might the following be sufficient to fix the issue? Since all that's causing it is that there is literally no data.
```context['updated'] = context['competition_bot_matchups'][0].updated if context['competition_bot_matchups'] else "Never"```

This stops the error and results in this:
![image](https://user-images.githubusercontent.com/13944193/107842739-918b5f00-6e19-11eb-8330-e99cc5f8a2e8.png)
